import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { WebView } from 'react-native-webview';

import { ActionRow, ActionSheet, NativeChromeGap, PrimaryButton, Screen, Sheet } from '../components/Primitives';
import { radius, type TempoTheme } from '../theme';
import type { RSSArticle, RSSFolder, RSSSubscription, TempoCommand } from '../types';

export function RSSScreen({ theme, articles, subscriptions, folders, phase, command, consumeCommand, perform }: {
  theme: TempoTheme; articles: RSSArticle[]; subscriptions: RSSSubscription[]; folders: RSSFolder[]; phase: string;
  command?: TempoCommand; consumeCommand: () => void; perform: <T>(action: string, payload?: Record<string, unknown>) => Promise<T>;
}) {
  const [query, setQuery] = useState(''); const searchRef = useRef<TextInput>(null); const [feed, setFeed] = useState<string>(); const [article, setArticle] = useState<RSSArticle>(); const [adding, setAdding] = useState(false); const [optionsVisible, setOptionsVisible] = useState(false); const [url, setURL] = useState('');
  useEffect(() => {
    if (command?.type === 'search') requestAnimationFrame(() => searchRef.current?.focus());
    if (command?.type === 'options') setOptionsVisible(true);
    if (command) consumeCommand();
  }, [command, consumeCommand]);
  const shown = useMemo(() => articles.filter((item) => !feed || item.feedID === feed).filter((item) => `${item.title} ${item.feedTitle} ${item.summary}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => (b.publishedAt ?? b.fetchedAt).localeCompare(a.publishedAt ?? a.fetchedAt)), [articles, feed, query]);
  return <Screen theme={theme}>
    <NativeChromeGap />
    <View style={styles.heading}><Text style={[styles.title, { color: theme.text }]}>阅读</Text><Text style={[styles.subtitle, { color: theme.secondary }]}>{articles.filter((item) => !item.isRead).length} 篇未读 · {subscriptions.length} 个来源</Text></View>
    <View style={[styles.search, { backgroundColor: theme.surfaceMuted }]}><Text style={[styles.searchIcon, { color: theme.tertiary }]}>⌕</Text><TextInput ref={searchRef} value={query} onChangeText={setQuery} returnKeyType="search" clearButtonMode="while-editing" placeholder="搜索标题、来源或摘要" placeholderTextColor={theme.tertiary} style={[styles.searchInput, { color: theme.text }]} /></View>
    <View><FlatList horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters} data={[{ id: '', title: '全部' }, ...subscriptions]} keyExtractor={(item) => item.id} renderItem={({ item }) => <Pressable onPress={() => setFeed(item.id || undefined)} style={[styles.filter, { backgroundColor: feed === (item.id || undefined) ? theme.accentSoft : theme.surfaceMuted }]}><Text style={{ color: feed === (item.id || undefined) ? theme.accent : theme.secondary, fontWeight: '600' }}>{item.title}</Text></Pressable>} /></View>
    <FlatList data={shown} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={phase === 'refreshing'} onRefresh={() => perform('rss.refresh')} tintColor={theme.accent} />} contentContainerStyle={shown.length ? styles.articles : styles.empty} ListEmptyComponent={<Text style={[styles.emptyText, { color: theme.secondary }]}>暂时没有文章，下拉刷新或添加订阅。</Text>} renderItem={({ item }) => <ArticleRow theme={theme} article={item} onPress={async () => { const full = await perform<RSSArticle>('rss.article', { id: item.id }); setArticle(full); }} />} />
    <Sheet visible={!!article} onClose={() => setArticle(undefined)} theme={theme}>{article ? <Reader theme={theme} article={article} perform={perform} /> : null}</Sheet>
    <Sheet visible={adding} onClose={() => setAdding(false)} theme={theme}><View style={styles.addBody}><Text style={[styles.sheetTitle, { color: theme.text }]}>添加 RSS 订阅</Text><TextInput autoCapitalize="none" keyboardType="url" value={url} onChangeText={setURL} placeholder="https://example.com/feed.xml" placeholderTextColor={theme.tertiary} style={[styles.urlInput, { color: theme.text, backgroundColor: theme.surface }]} /><PrimaryButton theme={theme} label="添加订阅" disabled={!url.trim()} onPress={async () => { await perform('rss.add', { url: url.trim() }); setURL(''); setAdding(false); }} /></View></Sheet>
    <ActionSheet visible={optionsVisible} onClose={() => setOptionsVisible(false)} theme={theme} title="阅读选项">
      <ActionRow theme={theme} title="添加订阅" detail="通过 RSS 地址添加新的内容来源" onPress={() => { setOptionsVisible(false); setAdding(true); }} />
      <ActionRow theme={theme} title="刷新全部" detail="立即检查所有订阅的新文章" onPress={() => { setOptionsVisible(false); void perform('rss.refresh'); }} />
      <ActionRow theme={theme} title={feed ? "将此来源全部标为已读" : "全部标为已读"} detail={feed ? "只处理当前选中的订阅" : "清空当前未读计数"} onPress={() => { setOptionsVisible(false); void perform('rss.markAllRead', feed ? { feedID: feed } : undefined); }} />
      {query ? <ActionRow theme={theme} title="清除搜索" onPress={() => { setQuery(''); setOptionsVisible(false); }} /> : null}
    </ActionSheet>
  </Screen>;
}
function ArticleRow({ theme, article, onPress }: { theme: TempoTheme; article: RSSArticle; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.article, { backgroundColor: theme.surface, opacity: pressed ? .64 : 1 }]}><View style={styles.articleMeta}><View style={styles.feedLine}>{!article.isRead ? <View style={[styles.unreadDot, { backgroundColor: theme.accent }]} /> : null}<Text style={[styles.feed, { color: theme.secondary }]}>{article.feedTitle}</Text></View><Text style={[styles.date, { color: theme.tertiary }]}>{relativeDate(article.publishedAt ?? article.fetchedAt)}</Text></View><Text numberOfLines={2} style={[styles.articleTitle, { color: theme.text, fontWeight: article.isRead ? '500' : '700' }]}>{article.title}</Text><Text numberOfLines={2} style={[styles.summary, { color: theme.secondary }]}>{stripHTML(article.summary)}</Text></Pressable>; }
function Reader({ theme, article, perform }: { theme: TempoTheme; article: RSSArticle; perform: <T>(action: string, payload?: Record<string, unknown>) => Promise<T> }) {
  const web = useRef<WebView>(null); const [loading, setLoading] = useState(false); const [summary, setSummary] = useState('');
  async function translate() { setLoading(true); web.current?.injectJavaScript(EXTRACT_SCRIPT); }
  async function message(event: { nativeEvent: { data: string } }) { try { const data = JSON.parse(event.nativeEvent.data) as { type: string; segments: string[] }; if (data.type !== 'tempoTranslate') return; const translated = await perform<string[]>('rss.translate', { segments: data.segments }); web.current?.injectJavaScript(`window.__tempoApply(${JSON.stringify(translated)});true;`); } finally { setLoading(false); } }
  return <View style={styles.reader}><View style={styles.readerToolbar}><Pressable onPress={async () => { setLoading(true); try { setSummary(await perform<string>('rss.summarize', { id: article.id })); } finally { setLoading(false); } }}><Text style={[styles.tool, { color: theme.accent }]}>AI 摘要</Text></Pressable><Pressable onPress={translate}><Text style={[styles.tool, { color: theme.accent }]}>翻译正文</Text></Pressable>{loading ? <ActivityIndicator color={theme.accent} /> : null}</View>{summary ? <View style={[styles.summaryBox, { backgroundColor: theme.accentSoft }]}><Text style={[styles.summaryText, { color: theme.text }]}>{summary}</Text></View> : null}<WebView ref={web} source={article.link ? { uri: article.link } : { html: article.content ?? article.summary }} onMessage={message} injectedJavaScript={CLEAN_SCRIPT} sharedCookiesEnabled allowsBackForwardNavigationGestures style={{ backgroundColor: theme.background }} /></View>;
}
const CLEAN_SCRIPT = `(function(){var s=document.createElement('style');s.innerHTML='header,nav,footer,aside,.sidebar,.newsletter,.cookie,.social-share{display:none!important} body{max-width:760px;margin:auto;padding:20px;font:18px/1.75 -apple-system,BlinkMacSystemFont,sans-serif} img{max-width:100%;height:auto}';document.head.appendChild(s);window.__tempoApply=function(v){var n=[].slice.call(document.querySelectorAll('article p,article li,main p,main li'));n.forEach(function(x,i){if(v[i])x.textContent=v[i]})}})();true;`;
const EXTRACT_SCRIPT = `(function(){var n=[].slice.call(document.querySelectorAll('article p,article li,main p,main li')).filter(function(x){return x.innerText.trim().length>2});window.ReactNativeWebView.postMessage(JSON.stringify({type:'tempoTranslate',segments:n.map(function(x){return x.innerText.trim()}).slice(0,120)}))})();true;`;
function stripHTML(value: string) { return value.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim(); }
function relativeDate(value: string) { const hours = Math.max(0, (Date.now() - new Date(value).getTime()) / 36e5); return hours < 1 ? '刚刚' : hours < 24 ? `${Math.floor(hours)} 小时前` : `${Math.floor(hours / 24)} 天前`; }
const styles = StyleSheet.create({ heading: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 12 }, title: { fontSize: 32, fontWeight: '700', letterSpacing: -.8 }, subtitle: { fontSize: 14, marginTop: 7 }, search: { marginHorizontal: 20, height: 44, borderRadius: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 8 }, searchIcon: { fontSize: 21, marginTop: -2 }, searchInput: { flex: 1, fontSize: 16 }, filters: { paddingHorizontal: 20, paddingVertical: 14, gap: 8 }, filter: { height: 34, borderRadius: 17, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' }, articles: { paddingHorizontal: 20, paddingBottom: 110 }, article: { padding: 18, borderRadius: 20, marginBottom: 12 }, articleMeta: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 9 }, feedLine: { flexDirection: 'row', alignItems: 'center', flexShrink: 1 }, unreadDot: { width: 6, height: 6, borderRadius: 3, marginRight: 7 }, feed: { fontSize: 12, fontWeight: '600', flexShrink: 1 }, date: { fontSize: 12, marginLeft: 12 }, articleTitle: { fontSize: 17, lineHeight: 23, letterSpacing: -.15 }, summary: { fontSize: 14, lineHeight: 20, marginTop: 7 }, empty: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 40 }, emptyText: { textAlign: 'center', lineHeight: 23 }, addBody: { flex: 1, paddingTop: 18 }, sheetTitle: { fontSize: 28, fontWeight: '700', paddingHorizontal: 20, marginBottom: 18 }, urlInput: { marginHorizontal: 20, borderRadius: radius.medium, height: 56, paddingHorizontal: 16, marginBottom: 18, fontSize: 16 }, reader: { flex: 1 }, readerToolbar: { height: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 24 }, tool: { fontSize: 15, fontWeight: '600' }, summaryBox: { marginHorizontal: 16, borderRadius: 16, padding: 14, marginBottom: 8 }, summaryText: { fontSize: 14, lineHeight: 21 }, });
